backend:
  name: github
  repo: EliseyMartynov/hram-nino
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/assets
public_folder: assets
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }